GET http://localhost:3003/ping
###

GET http://localhost:3003/songs
###


POST http://localhost:3003/bands
Content-Type: application/json

{
    "id": "b004",
    "name": "Rammstein"
}
###


GET http://localhost:3003/bands
###

PUT http://localhost:3003/bands/b001
Content-Type: application/json

{
    "id": "b001",
    "name": "Nova Banda"
}
###

GET http://localhost:3003/songs
###

POST http://localhost:3003/songs
Content-Type: application/json

{
    "id": "s006",
    "name": "Mutter",
    "bandId": "b004"
}
###

